export const SIM_CONFIG = {
  gridSize: 20,
  tickInterval: 200,
  initialSmiths: 3,
  replicationInterval: 20,
  maxSmiths: 30,
  shockwaveCooldown: 30,
  shockwaveRadius: 4,
  shockwaveKnockback: 5,
  bulletTimeUses: 2,
  bulletTimeDuration: 5,
  bulletTimeTriggerThreshold: 5,
  bulletTimeRange: 3,
  dodgeCooldown: 5,
  surroundTrigger: 3,
  surroundRange: 2,
  survivalTarget: 300,
  autoRestart: true,
  huntPhaseEnd: 50,
  replicationPhaseEnd: 150,
} as const;
